const CONFIG={npiToProducts:{"FY26 Spring NPI":["MacBook Neo","MacBook Air M5","MacBook Pro M5 Pro/Max","iPhone 17e","iPad Air M4"],"FY25 Fall NPI":["iPhone 17 Series","Watch Series","MacBook Pro M5","iPad Pro M5"]},defaultNPI:"FY25 Fall NPI",defaultProduct:"iPhone 17 Series",tabs:["Overview","Intent details","Product mix","Price related"],pages:{"Overview":"npi_overview.html","Intent details":"npi_intent_details.html","Product mix":"npi_product_mix.html","Price related":"npi_price_related.html"}};
let npi=CONFIG.defaultNPI,product=CONFIG.defaultProduct,tab="Intent details";
const $=id=>document.getElementById(id);
function render(){const ns=$("npi"),ps=$("product"),tabs=$("tabs");ns.innerHTML=Object.keys(CONFIG.npiToProducts).map(x=>`<option ${x===npi?'selected':''}>${x}</option>`).join('');ps.innerHTML=(CONFIG.npiToProducts[npi]||[]).map(x=>`<option ${x===product?'selected':''}>${x}</option>`).join('');tabs.innerHTML=CONFIG.tabs.map(x=>`<button class="tab ${x===tab?'active':''}" data-tab="${x}">${x}</button>`).join('');$("frame").src=CONFIG.pages[tab];}
function bind(){$("npi").onchange=e=>{npi=e.target.value;const list=CONFIG.npiToProducts[npi]||[];if(!list.includes(product))product=list[0]||'';render()};$("product").onchange=e=>product=e.target.value;$("tabs").onclick=e=>{if(e.target.dataset.tab){tab=e.target.dataset.tab;render()}};$("ask").onclick=toggleChat;$("close-chat").onclick=toggleChat;$("send").onclick=send;$("question").onkeydown=e=>{if(e.key==='Enter')send()}}
async function health(){const pill=$("mcp");try{const h=await vocMCP.checkHealth();if(!h.ok)throw Error();pill.classList.remove('off');$("mcp-text").textContent=`VOC MCP · ${h.latency}ms`}catch{pill.classList.add('off');$("mcp-text").textContent='VOC MCP offline'}}
function toggleChat(){$("drawer").classList.toggle('open')}
function addMsg(role,text){const d=document.createElement('div');d.className=`msg ${role}`;d.textContent=text;$("messages").appendChild(d);$("messages").scrollTop=$("messages").scrollHeight}
async function send(){const q=$("question").value.trim();if(!q)return;addMsg('user',q);$("question").value='';try{const r=await vocMCP.chatWithLLM(q,$("model").value);addMsg('',r.answer||'No response')}catch(e){addMsg('',`请求失败：${e.message}`)}}
render();bind();health();
